name: Back-end CI/CD
on:
  push:
    branches:
      - main
      
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
    backend_build_analyze:
     runs-on: ubuntu-latest

     defaults:
      run:
        working-directory: back
        
     steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: 'zulu' # Alternative distribution options are available.
            
        - name: Cache SonarCloud packages
          uses: actions/cache@v3
          with:
            path: ~/.sonar/cache
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar
            
        - name: Cache Maven packages
          uses: actions/cache@v3
          with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2

        - name: Compile the code
          run: mvn compile
          
        - name: Run tests and generate Jacoco report
          run: mvn verify
          
        - name: Package the code
          run: mvn package
        
        #- name: Build and Test with Maven
        #  run: mvn -B clean verify
          
        - name: Upload Jacoco Report
          uses: actions/upload-artifact@v4
          with:
            name: jacoco-report
            path: back/target/site/jacoco

          
        - name: Sonar analyze
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          run: org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=bobapp-ocr_Back 
  

    docker_build_and_push:
      needs: backend_build_analyze
      runs-on: ubuntu-latest
      steps:
              
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
                 
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
      
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: ./back
            file: ./back/Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/back_bobapp:latest
