name: FrontEnd CI CD

on:
  push:
    paths:
      - 'front/**'
      - '.github/workflows/**'
    branches:
      - main
  pull_request:
    paths:
      - 'front/**'
      - '.github/workflows/**'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  frontend_build_test_analyze:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular Project
        run: npm run build

      - name: Run Tests and Generate Code Coverage Report
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: front-coverage-report
          path: front/coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: front
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: frontend_build_test_analyze
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: front
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}

  docker_build_and_push:
    needs: frontend_build_and_test_analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp_front:latest

      - name: List files in Docker context
        run: ls -R ./front
        # Vérifie que le Dockerfile et les autres fichiers nécessaires existent
